apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}-svc
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.containerPorts.http }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
